class AppSecrets{
  static const SUPA_BASE_URL = "https://ybrpbicqkfjcuujztdxr.supabase.co";
  static const SUPA_BASE_ANNON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlicnBiaWNxa2ZqY3V1anp0ZHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTUxMjIsImV4cCI6MjA1ODIzMTEyMn0.pL5O2uvpLoHQo7SCIr70IjUGdVw87XOXZXX0ga8ewaA";
}